In [30]:
from sklearn.preprocessing import normalize
import torch
import numpy as np

In [3]:
lb_score = np.array([0.618,0.618,0.77,0.52]) #univ, yolox

In [28]:
lb_score = np.array([0.618]*3 + [0.77,0.52])

In [31]:
norm2 = normalize(lb_score[:,np.newaxis], axis=0).ravel()

In [27]:
norm2

array([0.48447899, 0.48447899, 0.60363887, 0.40765222])

In [32]:
norm2

array([0.43600425, 0.43600425, 0.43600425, 0.54324154, 0.36686442])

In [33]:
import json

In [34]:
with open('/opt/ml/detection/dataset/pseudo_test.json','r') as f:
    pseudo = json.load(f)

In [36]:
len(pseudo['annotations'])

14520

In [37]:
with open('/opt/ml/detection/dataset/train.json','r') as f:
    train = json.load(f)

In [38]:
len(train['annotations'])

23144

In [42]:
with open('/opt/ml/detection/mmdetection_new/boostcamp/work_dirs/multi_scale_HTC_swinB_pafpn_full_batch/epoch_40.pth','rb') as f:
    a = torch.load(f)

In [52]:
for k in a['state_dict'].keys():
    print(k)

backbone.patch_embed.projection.weight
backbone.patch_embed.projection.bias
backbone.patch_embed.norm.weight
backbone.patch_embed.norm.bias
backbone.stages.0.blocks.0.norm1.weight
backbone.stages.0.blocks.0.norm1.bias
backbone.stages.0.blocks.0.attn.w_msa.relative_position_bias_table
backbone.stages.0.blocks.0.attn.w_msa.relative_position_index
backbone.stages.0.blocks.0.attn.w_msa.qkv.weight
backbone.stages.0.blocks.0.attn.w_msa.qkv.bias
backbone.stages.0.blocks.0.attn.w_msa.proj.weight
backbone.stages.0.blocks.0.attn.w_msa.proj.bias
backbone.stages.0.blocks.0.norm2.weight
backbone.stages.0.blocks.0.norm2.bias
backbone.stages.0.blocks.0.ffn.layers.0.0.weight
backbone.stages.0.blocks.0.ffn.layers.0.0.bias
backbone.stages.0.blocks.0.ffn.layers.1.weight
backbone.stages.0.blocks.0.ffn.layers.1.bias
backbone.stages.0.blocks.1.norm1.weight
backbone.stages.0.blocks.1.norm1.bias
backbone.stages.0.blocks.1.attn.w_msa.relative_position_bias_table
backbone.stages.0.blocks.1.attn.w_msa.relative_p

In [51]:
a['state_dict'].keys

OrderedDict([('backbone.patch_embed.projection.weight',
              tensor([[[[ 0.0291,  0.0530, -0.0227, -0.0335],
                        [ 0.0137,  0.0545,  0.0165,  0.0397],
                        [-0.0227, -0.0072,  0.0153,  0.0083],
                        [-0.0544, -0.0523, -0.0644,  0.0036]],
              
                       [[-0.0035,  0.0275, -0.0563, -0.0675],
                        [ 0.0356,  0.0804,  0.0115,  0.0368],
                        [-0.0143,  0.0032,  0.0148, -0.0036],
                        [-0.0429, -0.0238, -0.0209,  0.0272]],
              
                       [[-0.0380, -0.0208, -0.0583, -0.0607],
                        [-0.0077,  0.0426,  0.0263,  0.0413],
                        [-0.0075, -0.0077,  0.0276,  0.0132],
                        [-0.0186,  0.0019,  0.0144,  0.0319]]],
              
              
                      [[[-0.0893,  0.0450,  0.0686,  0.0968],
                        [-0.0324,  0.0076, -0.0405, -0.0346],
            